# docker-compose.wp.yml
# This file is used to set up a WordPress environment with a MySQL database and phpMyAdmin for database management.
# It includes a WordPress service, a MySQL database service,
# and a phpMyAdmin service for easy database management.
services:
  wp:
    image: wordpress:6.5-php8.1-apache
    ports: ["8080:80"]
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ENVIRONMENT_TYPE', 'local');    
      WORDPRESS_DB_HOST: dbwp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./plugin-woo:/var/www/html/wp-content/plugins/gmc-shield
  dbwp:
    image: mysql:8
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbwp_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    ports: ["8081:80"]
    environment:
      PMA_HOST: dbwp
volumes:
  dbwp_data:
